# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: rouge

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'Parham Alvani'
tagline:          'Parham Alvani Homepage'
description:      'Parham Alvani Personal Homepage'
url:              'http://1995parham.github.io'
baseurl:          ''

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/
- text: Downloads
  url: /downloads/
- text: Resume (PDF)
  url: /resume-pdf/parham-cv.pdf

# Author Details
author:         'Parham Alvani'
yahoomail:      'mailto:parham.alvani@yahoo.com'
workmail:       'mailto:parham.alvani@aut.ac.ir'
hotmail:        'mailto:parham.alvani@hotmail.com'
gmail:          'mailto:parham.alvani@gmail.com'

# Disqus
disqushandler: '1995parham'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.7.9
